Wrap some unit test data structures in a flag.
optimizely/objective-c-sdk pull request #193
Opened 2017-11-08 01:25 UTC by alda-optimizely

The data structures used for the backoff retry tests are not threadsafe, so I wrapped them in a flag that checks if unit tests are running. This was causing a crash if there's a backoff retry in datafile download or event dispatch.

2017-11-09 18:28 UTC, kellyroach-optimizely commented
TEST:
* sh ./Scripts/build_all.sh
==> ** BUILD SUCCEEDED **
* sh ./Scripts/local_travis.sh
==> ** TEST SUCCEEDED **
* 8 iOS	test suites PASSED
* OptimizelySDKiOSUniversalTests PASSED

The code changes submitted in this P.R. also appear to be a compelling and plausible
explanation and resolution of OASIS-2002 and "Fatal Exception: NSRangeException in OPTLYHTTPRequestManager.m" issue posted on GITHUB.COM .

2017-11-09 18:28 UTC, kellyroach-optimizely approved these changes

2017-11-09 19:16 UTC, alda-optimizely commented
Yes. This fix is for that bug.

2017-11-09 20:08 UTC, thomaszurkan-optimizely requested changes

2017-11-09 20:08 UTC, thomaszurkan-optimizely commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYHTTPRequestManager.m
> +        self.delaysTest[backoffRetryAttempt] = [NSNumber numberWithLongLong:delay_ns];
I think you should still have a test to see if backOffRetryAttempt is larger than the size of delaysTest (just as a sanity check)

2017-11-15 23:38 UTC, thomaszurkan-optimizely approved these changes

2017-11-16 05:22 UTC, merged