Notification center
optimizely/objective-c-sdk pull request #210
Opened 2018-01-17 10:44 UTC by AbdurRafay

* Listeners added

* Send notifications

* Test cases

* Test case for sendNotifications

* refactoring

* copyrights changed

* redesigned

* fixes - after merge

* fix - file references

2018-01-17 10:55 UTC, AbdurRafay commented on OptimizelySDKCore/OptimizelySDKCore/Optimizely.m
>  }
In order to implement variable arguments in sendNotifications method, I make sure no argument could be pass as nil which can break the argument list.

2018-01-17 10:57 UTC, AbdurRafay commented on OptimizelySDKCore/OptimizelySDKCore/Optimizely.m
>      return variation;
Same here.
In order to implement variable arguments in sendNotifications method, I make sure no argument could be pass as nil which can break the argument list.

2018-01-18 18:46 UTC, msohailhussain commented
@thomaszurkan-optimizely @kellyroach-optimizely Can you please review this PR.

2018-01-19 18:18 UTC, kellyroach-optimizely commented
This is for OASIS-2080 .

2018-01-19 19:09 UTC, thomaszurkan-optimizely requested changes
This PR looks good for the Notificaiton Listeners part.  But, there are feature variable checkins.  Can we separate that?

2018-01-19 21:19 UTC, thomaszurkan-optimizely approved these changes
Never mind, I see that it is just formatting and no code change.  So, I'm approving!  thanks!

2018-01-22 18:38 UTC, kellyroach-optimizely commented
ISSUE: Use OPTLYLogger and programmed error recovery instead of "assert"

The P.R. #210 would add many "assert"s to OPTLYNotificationCenter.m but this
would be precedent setting for the SDK .  It could be discussed, but I think I would
not like to see this happen.

Instead, use OPTLYLogger for logging failed a modest but appropriate number
of input sanity checks like most of the rest of the iOS SDK code does, and arrange
that callers of your code do recover gracefully (do not crash) if OPTLYNotificationCenter
methods reject some occasional incorrect inputs.  Large complex software in the
modern era should do this because glitches are inevitable.

OPTLYNotificationCenter does have a
@property (nonatomic, strong) id<OPTLYLogger> logger
The constructor for OPTLYNotificationCenter ought to have a signature like
- (instancetype) initWithProjectConfig:(OPTLYProjectConfig *)config
Then the OPTLYNotificationCenter instance methods themselves should use the config.logger .

OPTLYNotificationCenter should not create its own logger but use the logger
provided by the OPTLYProjectConfig that Optimizely was initialized with.

Therefore, I would like to ask that "assert" not be used in checked in code.
Instead, use OPTLYLogger and programmed error recovery for diagnostics
and avoidance of iOS SDK crashing apps in the field.

2018-01-22 18:58 UTC, kellyroach-optimizely commented
ISSUE: Use NSArray inputs instead of va_list va_start va_end

Function sendNotifications:args: is using variable-length argument lists with signature
- (void)sendNotifications:(OPTLYNotificationType)type args:(id)firstArg, ...
and relying on using va_list va_start va_end in its body.

For the most part, the iOS SDK avoids va_list va_start va_end, and I think that is a
good practice.  There are a number of reasons.  One reason is that "..." doesn't
allow functional composition.  IOW, the output of one function which could be an
array, can't be used as the input args to sendNotifications:args: as it is currently coded.

2018-01-22 19:01 UTC, kellyroach-optimizely requested changes
I have 3 main issues with P.R. #210 .
ISSUE: Use OPTLYLogger and programmed error recovery instead of "assert"
ISSUE: Use NSArray inputs instead of va_list va_start va_end
ISSUE: Use OOP object delegates instead of function pointers

2018-01-22 19:47 UTC, kellyroach-optimizely commented
ISSUE: Use OOP object delegates instead of function pointers

OPTLYActivateNotificationListener and OPTLYTrackNotificationListener in
OPTLYNotificationCenter.h are C function pointer types and are being used
in the method signatures
- (NSInteger)addNotification:(OPTLYNotificationType)type activateListener:(OPTLYActivateNotificationListener)activateListener
- (NSInteger)addNotification:(OPTLYNotificationType)type trackListener:(OPTLYTrackNotificationListener)trackListener
in OPTLYNotificationCenter.m .

I think this raises some issues for OOP style and Swift translation.
I would like to suggest instead creating an Objective-C @protocol with
two method declarations essentially equivalent to the two C function pointer types
you are trying to introduce, and then redeclare the two OPTLYNotificationCenter.m
method signatures to input arguments conforming to this Objective-C @protocol .
E.G. if we name the protocol "OPTLYNotificationDelegate" then the two method
signatures can input "id<OPTLYNotificationDelegate> activateListener" and
"id<OPTLYNotificationDelegate> trackListener" instead.

2018-01-22 19:49 UTC, kellyroach-optimizely commented on OptimizelySDKCore/OptimizelySDKCoreTests/OPTLYNotificationCenterTest.m
> +    [_notificationCenter clearAllNotifications];
Some code comments mention "ClearAllNotifications", but should say "clearAllNotifications"
with lower case "c" .

2018-01-26 23:20 UTC, kellyroach-optimizely commented
CODE REVIEW 180126 AFTER https://github.com/optimizely/objective-c-sdk/pull/210/commits/cfbfe24ff5d44f3eceb80a773bdf1c4c347e6e25

The updated P.R. #210 is very much improved.  Thank you!

I did spot a couple little more items that could be fixed.  These items pertain mainly
to the OPTLYActivateNotificationTest and public notificationsCount .  See comments
about these below.

2018-01-26 23:22 UTC, kellyroach-optimizely commented
OPTLYActivateNotificationTest COMPILER WARNINGS
```
.../OptimizelySDKCore/OptimizelySDKCoreTests/OPTLYNotificationCenterTest.m:36:17: warning: class 'OPTLYActivateNotificationTest' does not conform to protocol 'OPTLYNotificationDelegate' [-Wprotocol]
@implementation OPTLYActivateNotificationTest
                ^
.../OptimizelySDKCore/OptimizelySDKCoreTests/OPTLYNotificationCenterTest.m:36:17: note: add stubs for missing protocol requirements
@implementation OPTLYActivateNotificationTest
                ^
.../OptimizelySDKCore/OptimizelySDKCoreTests/OPTLYNotificationCenterTest.m:44:17: warning: class 'OPTLYTrackNotificationTest' does not conform to protocol 'OPTLYNotificationDelegate' [-Wprotocol]
@implementation OPTLYTrackNotificationTest
                ^
.../OptimizelySDKCore/OptimizelySDKCoreTests/OPTLYNotificationCenterTest.m:44:17: note: add stubs for missing protocol requirements
@implementation OPTLYTrackNotificationTest
                ^
2 warnings generated.
```

2018-01-26 23:31 UTC, kellyroach-optimizely commented
COMMENT ABOUT PUBLIC "notificationsCount"
```
@property (nonatomic, readonly) NSUInteger notificationsCount;
```
This property is publicly exposed in OPTLYNotificationCenter.h .   However,
our Notification Center design doc does not ask for this, sibling reference python-sdk
does not implement this, and I also asked Thomas Zurkan who wrote the design doc
about "notificationsCount" .  Tom Zurkan didn't think "notificationsCount" is necessary.

Since I do see the "notificationsCount" is being used by the OPTLYActivateNotificationTest
which is only a unit test and not part of our shipped SDK *.framework, I'm wondering and
would like to suggest to you that "notificationsCount" could be moved out of
OPTLYNotificationCenter.m+.h and into OPTLYActivateNotificationTest.m instead as
member of a private OPTLYNotificationCenter extension category visible only to
OPTLYActivateNotificationTest.m .  Could you consider doing this?

2018-01-29 11:58 UTC, AbdurRafay commented
I moved out "notificationsCount" from OPTLYNotificationCenter.h and made it a private member of OPTLYNotificationCenter extension in OPTLYNotificationCenterTest.m

Since its implementation in OPTLYNotificationCenter.m also used other private members of OPTLYNotificationCenter like ("notifications") which then should also be exposed in extension.

2018-01-29 18:55 UTC, kellyroach-optimizely commented
TEST:
* sh .Scripts/build_all.sh PASSED
* sh .Scripts/local_travis.sh PASSED
* OPTLYNotificationCenterTest.m zero warnings PASSED
* 4 Analyze PASSED
* 8+1 iOS test suites PASSED
* 7+1 tvOS test suites PASSED
* 2 DemoApp's PASSED

All code review comments addressed.  APPROVING.

2018-01-29 18:55 UTC, kellyroach-optimizely approved these changes

2018-01-29 18:55 UTC, merged