Kroach/oasis 2442 xcode94
optimizely/objective-c-sdk pull request #254
Opened 2018-06-02 00:56 UTC by kellyroach-optimizely

PULL REQUEST ACCOMPLISHES:
* Auto-fix project settings updates for Xcode 9.4 .
* Get both Xcode 9.4 Build warnings and Xcode 9.4 Analyze warnings to "No issues"
on the SDK framework targets.

2018-06-02 01:13 UTC, kellyroach-optimizely commented
TEST:
* sh ./Scripts/build_all.sh PASSED
* 4 Analyze PASSED
* 8+1 iOS test suites PASSED
* 7+1 tvOS test suites PASSED
* 2 demo apps run (8415331295) PASSED
* 2 demo apps predicted results on OPTIMIZELY.COM PASSED
                   iOS    tvOS
    variation_a    0/5    0/13
    variation_b    3/4    8/8
* 2 "iTunes Connect" "Validate..." PASSED
* Carthage installation into ~/OptimizelyCarthageTest app PASSED
                   iOS
    variation_a    0/35
    variation_b    27/30
* ~/OptimizelyCarthageTest app "iTunes Connect" "Validate..." PASSED

2018-06-05 21:57 UTC, thomaszurkan-optimizely requested changes
One possible retain cycle where we access self inside a block.

2018-06-05 21:57 UTC, thomaszurkan-optimizely commented on OptimizelySDKEventDispatcher/OptimizelySDKEventDispatcher/OPTLYEventDispatcher.m
> +            [self->_logger logMessage:logMessage withLevel:OptimizelyLogLevelDebug];
shouldn't these be weakSelf or at least reference we self and then assign to strong self in block?

2018-06-05 23:50 UTC, thomaszurkan-optimizely requested changes

2018-06-05 23:50 UTC, thomaszurkan-optimizely commented on OptimizelySDKEventDispatcher/OptimizelySDKEventDispatcher/OPTLYEventDispatcher.m
> +        typeof(self) strongSelf = weakSelf;
I know this is a nit but could you change it so that you assign strong self and then do a 
if (!strongSelf) return; 
instead of wrapping the if.

2018-06-07 21:08 UTC, thomaszurkan-optimizely approved these changes
LGTM

2018-06-07 22:11 UTC, merged