Add environments support to SDK with SDK key initialization
optimizely/objective-c-sdk pull request #264
Opened 2018-06-13 20:17 UTC by mikeng13

2018-06-15 23:41 UTC, kellyroach-optimizely requested changes

2018-06-15 23:41 UTC, kellyroach-optimizely commented on OptimizelySDKShared/OptimizelySDKShared/NSString+OPTLYCategory.h
> +- (BOOL)isValidKeyString;
COMPILING OptimizelySDKiOSUniversal TARGET GETS "warning: umbrella header"

```
<module-includes>:1:1: warning: umbrella header for module 'OptimizelySDKiOS' does not include header '/Users/kroach/objective-c-sdk-environments/OptimizelySDKShared/OptimizelySDKShared/NSString+OPTLYCategory.h' [-Wincomplete-umbrella]
#import "Headers/OptimizelySDKiOS.h"
^
1 warning generated.
1 warning generated.
```

NOTE: "... NSString+OPTLYCategory.h' [-Wincomplete-umbrella]"

2018-06-21 21:44 UTC, mikeng13 commented
Changes look good to me @kellyroach-optimizely

2018-06-22 19:07 UTC, kellyroach-optimizely commented
TEST:
* sh ./Scripts/build_all.sh (DONE in (16))
* 4 Analyze *.framework's PASSED
* 2 Analyze demo apps PASSED
* 8+1 iOS test suites PASSED (*)
* 7+1 tvOS test suites PASSED
* 2 demo apps run PASSED
* 2 demo apps predicted results on OPTIMIZELY.COM PASSED
```
               iOS    tvOS
variation_a    0/7    0/16
variation_b    9/9    11/11
```
* 2 demo apps "iTunes Connect" "Validate..." PASSED

2018-06-22 23:22 UTC, kellyroach-optimizely commented
TEST AGAIN
Due to the OPTLY_DATAFILE_URL commit.
* sh ./Scripts/build_all.sh PASSED
* 4 Analyze *.framework's PASSED
* 2 Analyze demo apps PASSED
* 8+1 iOS test suites PASSED
* iOS demo app (8415331295) predicted results on OPTIMIZELY.COM PASSED
```
               iOS
variation_a    0/14
variation_b    21/21
```

2018-06-22 23:28 UTC, kellyroach-optimizely commented
CODE REVIEW
Comparison with the referenced SDK android-sdk .
We'd summarize the objective-c-sdk changes by saying:
* In the new world, you can pass either of
    * projectId (the old way)
    * sdkKey (the new way)
to yield a "datafileConfig" internally which is passed around in the
places in the SDK which used to expect a mere "projectId" .  The
"datafileConfig" now plays this role.
* A valid datafileConfig is a (projectId,sdkKey) pair where
exactly one of these strings is non-nil valid string (isValidKeyString:).
That means not nil, not empty, and not containing space chars.

Two deviations of objective-c-sdk from the android-sdk were noted:
* Both SDK's are replacing internal use of "projectId" by something.
The objective-c-sdk is using datafileConfig .  The android-sdk is using
datafileConfigKey .  In an OOP, we think datafileConfig is preferable
and android-sdk could be slightly improved.  However, there isn't
that much difference.
* The objective-c-sdk objective-c-sdk is pickier about the
isValidKeyString: requiring
``((s != nil) && ![s isEqualToString:@""] && ![s containsString:@" "])``
whereas android-sdk is only checking for
``(s != null)``
We communicated this to Mike Ng.  We're told android-sdk should likely
be doing the same check as objective-c-sdk .

2018-06-22 23:29 UTC, kellyroach-optimizely commented
CONCLUDE: APPROVING
We have:
* Mike Ng's "Changes look good to me @kellyroach-optimizely"
* TEST PASSED
* CODE REVIEW PASSED

2018-06-22 23:29 UTC, kellyroach-optimizely approved these changes

2018-06-22 23:30 UTC, merged