deprecated static init methods and made initWithBuilder public
optimizely/objective-c-sdk pull request #272
Opened 2018-06-25 17:49 UTC by msohailhussain

Just for feedback.

2018-07-02 18:06 UTC, mikeproeng37 requested changes

2018-07-02 18:06 UTC, mikeng13 commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYProjectConfig.h
> ++ (nullable instancetype)init:(nonnull OPTLYProjectConfigBuilderBlock)builderBlock
Please update the license headers in all the files touched.

2018-07-02 18:06 UTC, mikeng13 commented on OptimizelySDKCore/OptimizelySDKCoreTests/OptimizelySDKCoreiOSTests-Bridging-Header.h
> +//
Please add a license header for this file

2018-07-02 18:06 UTC, mikeng13 commented on OptimizelySDKDatafileManager/OptimizelySDKDatafileManagerTests/OptimizelySDKDatafileManageriOSTests-Bridging-Header.h
> +//
License header

2018-07-12 17:33 UTC, mikeproeng37 approved these changes

2018-07-12 17:33 UTC, thomaszurkan-optimizely approved these changes
LGTM

2018-07-12 17:34 UTC, merged