explicit type check of NSNumber in getFeatureVariable...
optimizely/objective-c-sdk pull request #289
Opened 2018-08-02 17:09 UTC by AbdurRafay

If featureVariableBoolean has invalid value like "123" so it will be treated as false while converting from NSString to NSNumber.

2018-08-02 17:11 UTC, AbdurRafay commented
Same for featureVariableDouble & Integer.

2018-08-02 18:52 UTC, thomaszurkan-optimizely requested changes
I think we should just wrap the auto boxing with a try catch just to be safe and log the error.

2018-08-02 18:52 UTC, thomaszurkan-optimizely commented on OptimizelySDKCore/OptimizelySDKCore/Optimizely.m
> -    if (variableValue) {
I think I'd rather see a try catch where you log the error in the catch.

2018-08-07 21:08 UTC, tylerbrandt commented
build

2018-08-07 21:09 UTC, tylerbrandt commented
build

2018-08-07 21:11 UTC, tylerbrandt commented
build

2018-09-15 00:17 UTC, aliabbasrizvi commented
@thomaszurkan-optimizely this PR has been out for a while. What is the latest here?

2018-09-21 18:55 UTC, closed without merging