add credits for third party libraries
optimizely/objective-c-sdk pull request #299
Opened 2018-08-10 23:05 UTC by thomaszurkan-optimizely

2018-08-13 19:10 UTC, thomaszurkan-optimizely commented
build

2018-08-16 17:31 UTC, mikeproeng37 requested changes
Can you include a line about first party code and move the 3rd party deps to `Additional Code` 

https://github.com/optimizely/java-sdk/pull/204/files#diff-04c6e90faac2675aa89e2176d2eec7d8R95

2018-08-22 20:33 UTC, mikeproeng37 requested changes
Just one last thing and we're good to go

2018-08-22 20:33 UTC, mikeng13 commented on README.md
> +First-party code (under OptimizelySDKCore/, OptimizelySDKDatafileManager/, OptimizelySDKEventDispatcher/, OptimizelySDKiOS/, OptimizelySDKShared/, OptimizelySDKTVOS/, OptimizelySDKUniversal/, Optimiz
We no longer have code under `OptimizelySDKUserProfile`. I think we deprecated that in favor of `OptimizelySDKUserProfileService`

2018-08-22 20:59 UTC, mikeproeng37 approved these changes
lgtm

2018-08-23 23:36 UTC, spencerwilson-optimizely commented
Can this be merged?

2018-08-24 18:03 UTC, merged