fix(nullattributes): Accepting null attributes and eventTags
optimizely/objective-c-sdk pull request #335
Opened 2018-11-15 19:56 UTC by msohailhussain

Refactored code, added categories for validArray, validString, emptryString. 
NotificationListener should return those attributes what is sent by the end-user. It was returning empty dictionary if nil was sent.

2018-11-28 06:43 UTC, msohailhussain commented
@thomaszurkan-optimizely Can you please review this PR.

2018-11-30 01:37 UTC, jaeopt requested changes
It looks good to me other than issues commented.

2018-11-30 01:37 UTC, jaeopt commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYDecisionService.m
> +
Don't we need nil checking for "attributes" since it's changed nullable?
Why using for loop instead of a simple nil checking if statement?

2018-11-30 01:37 UTC, jaeopt commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYNSObject+Validation.h
> + * Determines if object is a valid string type.
clarify comment to [valid "non-empty" string type]

2018-11-30 01:37 UTC, jaeopt commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYNSObject+Validation.h
> + * Determines if object is a valid array type.
clarify comment to [valid "non-empty" array type]
and others below as well

2018-11-30 01:37 UTC, jaeopt commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYNotificationCenter.h
> +static NSString *const OPTLYNotificationExperimentKey = @"experiment";
Can we change these to global with extern to be consistent with other parts?

2018-11-30 01:37 UTC, jaeopt commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYNotificationCenter.h
> +static NSString *const OPTLYNotificationEventTags = @"eventTags";
Not sure about naming rules, but to be consistent, they should like:
OPTLYNotificationEventTags --> OPTLYNotificationEventTagsKey
OPTLYNotificationLogEventParams --> OPTLYNotificationLogEventParamsKey

2018-11-30 10:34 UTC, yasirfolio3 commented
Changes made as per suggestions, please review

2018-11-30 16:55 UTC, jaeopt approved these changes

2018-12-03 18:16 UTC, thomaszurkan-optimizely commented
build

2018-12-04 18:46 UTC, thomaszurkan-optimizely commented
build

2018-12-06 20:46 UTC, thomaszurkan-optimizely commented
build

2018-12-07 12:12 UTC, mfahadahmed commented
build

2018-12-11 19:16 UTC, thomaszurkan-optimizely approved these changes
LGTM

2018-12-11 19:30 UTC, merged