feat (audience match types): Update condition evaluator for new audience match types.
optimizely/objective-c-sdk pull request #336
Opened 2018-11-19 07:51 UTC by yasirfolio3

2018-11-30 14:23 UTC, aliabbasrizvi reviewed
Changes mostly look good to me. Would leave to @thomaszurkan-optimizely to take a closer look.

2018-11-30 14:26 UTC, thomaszurkan-optimizely requested changes
Why are there no unit tests?

2018-12-03 12:36 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCoreTests/TestData/test_data_25_experiments.json
> +{"experiments": [{"status": "Running", "layerId": "1234", "key": "testExperiment12", "trafficAllocation": [{"entityId": "6387320950", "endOfRange": 5000}, {"entityId": "6387320951", "endOfRange": 100
All "type": "custom_dimension" have been converted to "type": "custom_attribute".

2018-12-03 12:37 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYBaseCondition.m
> +-(nullable NSNumber *)evaluateMatchTypeExact:(NSDictionary<NSString *, NSObject *> *)attributes{
https://github.com/optimizely/objective-c-sdk/pull/336/files/ee42573da9a10454d12504f33a5b7eebfac054ed#diff-aa4be2fef28e62bdd60ccbf5094615e6R101
1. success defaults to null. 
2. Secondly isEqual is only called if both the value and userAttribute are of similar acceptable types i.e Numeric, Bool, String, Null

Testcase for condition mismatch can be found here:
https://github.com/optimizely/objective-c-sdk/pull/336/files#diff-b36e2d0d8afb118bc8ee016acb8a85cfR166

2018-12-03 12:38 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCore/OPTLYBaseCondition.m
>      if (attributes == nil) {
This is implemented in PR:
https://github.com/optimizely/objective-c-sdk/pull/337

2018-12-03 12:48 UTC, yasirfolio3 commented
Changes made, please review.

2018-12-07 12:12 UTC, mfahadahmed commented
build

2018-12-19 19:42 UTC, thomaszurkan-optimizely approved these changes
LGTM

2018-12-19 19:42 UTC, merged