feat(Audience Evaluation): JSON fix for null type in Leaf condition.
optimizely/objective-c-sdk pull request #355
Opened 2019-01-10 07:15 UTC by yasirfolio3

For JSON parsing of Leaf condition, mark property 'type' as optional. Return null if leaf condition is evaluated with property 'type' null.

2019-01-10 20:03 UTC, msohailhussain approved these changes
lgtm

2019-01-10 23:35 UTC, thomaszurkan-optimizely approved these changes

2019-01-11 19:22 UTC, msohailhussain commented
@thomaszurkan-optimizely we added some more fixes.

2019-01-11 19:25 UTC, thomaszurkan-optimizely requested changes
Please add a unit test that tests for the not condition on Experiment.AudienceConditions where the user passes in nil or empty attributes.  In the last round of testing this caused the condition to pass.  It should have been nil and therefor false.

2019-01-14 06:48 UTC, yasirfolio3 commented
Test-cases added for null or empty user attributes in Not condition, please review.

2019-01-15 05:08 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCoreTests/OPTLYConditionTest.m
> +    XCTAssertNil([notCondition evaluateConditionsWithAttributes:userAttributes projectConfig:self.optimizelyTypedAudience.config]);
The reason for this was that Evaluators for Experiment as well as Audiences were returning false if evaluation was null, which was then converted to true by the 'NOT' operator. Now all evaluators can return null aswell, and so when not operator recieves null as evaluation result, it returns null too. See change:

https://github.com/optimizely/objective-c-sdk/pull/355/files#diff-14f1494cb8efebbed033865e5c25e335R58
https://github.com/optimizely/objective-c-sdk/pull/355/files#diff-8749178f3084f0c32b0ea09b5615e095R32
https://github.com/optimizely/objective-c-sdk/pull/355/files#diff-e39e60da2e49e74d868de2fc69c31377R44

I have updated the testcases for activate call with not conditions aswell, please review.

2019-01-15 23:21 UTC, thomaszurkan-optimizely approved these changes
LGTM

2019-01-16 19:18 UTC, merged