ci: use travisci-tools script to trigger-fullstack-compat suite
optimizely/objective-c-sdk pull request #389
Opened 2019-03-22 11:09 UTC by yasirfolio3

2019-03-22 15:50 UTC, juancarlostong commented on .travis.yml
>        after_success: skip
```suggestion
      after_success: travis_terminate 0
```
we can terminate now that we arent using darwin

2019-03-22 15:52 UTC, juancarlostong requested changes

2019-03-22 15:52 UTC, juancarlostong commented on .travis.yml
> +      language: minimal
```suggestion
      language: minimal
      os: linux
```

2019-03-22 15:52 UTC, juancarlostong commented on .travis.yml
>        # travis_terminate not supported by darwin
```suggestion

```

2019-03-25 05:28 UTC, yasirfolio3 commented on .travis.yml
> +      language: minimal
Changes made.

2019-03-29 00:17 UTC, juancarlostong approved these changes

2019-03-29 00:48 UTC, merged