(fix): add support for TLS certificates pinning
optimizely/objective-c-sdk pull request #433
Opened 2019-07-25 23:32 UTC by jaeopt

## Summary
Some applications require support for TLS pinning for extra security. This fix allows opt-in for that feature.
 
- add opt-in settings (off by default - most applications do not need this)
- embed public root certificates and verify if certs not compromised when pinning is enabled.

## Test plan
- Add new unit tests for 4 combinations: {(disabled, good), (enabled, good), (disabled, bad), (enabled, bad)}
- Add FSC test suites

## Issues
- OASIS-5056

2019-07-31 13:26 UTC, yasirfolio3 requested changes
LGTM, just few nits.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKEventDispatcher/OptimizelySDKEventDispatcher/OPTLYEventDispatcher.h
> +/// Enable TLS pinning for extra security (do not turn this on unless you really need extra TLS security
(nit) Missing closing bracket.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKEventDispatcher/OptimizelySDKEventDispatcher/OPTLYEventDispatcherBuilder.h
> +/// Enable TLS pinning for extra security (do not turn this on unless you really need extra TLS security
(nit) missing closing bracket.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKShared/OptimizelySDKShared/OPTLYManagerBuilder.h
> +/// Enable TLS pinning for extra security (do not turn this on unless you really need extra TLS security
(nit) bracket missing.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKiOS/OptimizelySDKiOS/OPTLYManager.m
> +        // TLS pinnig is supported for iOS only (not tvOS)
(nit) change pinnig to pinning.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKiOS/OptimizelySDKiOSTests/OptimizelySDKiOSTLSPinningOptInTests.m
> + * Copyright 2016-2018, Optimizely, Inc. and contributors                   *
(nit) Please update the years.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKiOS/OptimizelySDKiOSTests/OptimizelySDKiOSTLSPinningOptInTests.m
> +- (void)testTLSPinngOptOut {
(nit) change Pinng to Pinning. Same for all test names.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKDatafileManager/OptimizelySDKDatafileManager/OPTLYDatafileManagerBuilder.h
> +/// Enable TLS pinning for extra security (do not turn this on unless you really need extra TLS security
(nit) Missing closing bracket.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKDatafileManager/OptimizelySDKDatafileManager/OPTLYDatafileManager.h
> +/// Enable TLS pinning for extra security (do not turn this on unless you really need extra TLS security
(nit) Missing closing bracket.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCoreTests/TLSPinningTests.m
> +// test with wrong root certficates
(nit): change certficates to certificates.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCoreTests/TLSPinningTests.m
> +// - when pinning is disabled (default), all connections to any ursl must be successful
(nit): change ursl to urls.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCoreTests/TLSPinningTests.m
> +#pragma mark - TLS Certficates Pinning Tests
(nit): change Certficates to Certificates.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCoreTests/TLSPinningTests.m
> +// test with correct root certficates
(nit): Certificates.

2019-07-31 13:26 UTC, yasirfolio3 commented on OptimizelySDKCore/OptimizelySDKCoreTests/TLSPinningTests.m
> + * Copyright 2016-2017, Optimizely, Inc. and contributors                   *
(nit): update years.

2019-10-22 19:08 UTC, closed without merging

2019-10-22 19:09 UTC, jaeopt commented
SSL pinning support is put on hold. We'll review the issue and solution again later.